"""
Export SB3 PPO Policy to ESP32 C Header
========================================
Extracts MLP weights + VecNormalize stats and writes a C header
that esp32_standalone.ino can #include for on-device inference.

Usage:
    python deploy/export_to_esp32.py models/trained/stage2_dr_final.zip \\
        --norm models/trained/vec_normalize_stage2_dr.pkl \\
        --out  firmware/esp32_standalone/model_weights.h

Memory footprint in ESP32 Flash (float32):
    H=64  :  ~21 KB
    H=128 :  ~72 KB
    H=256 : ~280 KB   (stored in .rodata / Flash, not SRAM)
"""

import argparse
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

from envs.drone_env import WhoopDroneEnv


# ─────────────────────────────────────────────────────────────────────────────

def _arr_to_c(name: str, arr: np.ndarray) -> str:
    """Convert numpy array to a C static const float array literal."""
    arr  = arr.astype(np.float32)
    flat = arr.flatten()
    vals = ", ".join(f"{v:.8g}f" for v in flat)
    if arr.ndim == 1:
        return f"static const float {name}[{arr.shape[0]}] = {{{vals}}};\n"
    r, c = arr.shape
    return (
        f"/* shape [{r}][{c}], row-major: access with {name}[row*{c}+col] */\n"
        f"static const float {name}[{r * c}] = {{{vals}}};\n"
    )


def export(model_path: str, vec_norm_path: str, out_path: str):
    # ── Load model ────────────────────────────────────────────────────────────
    model  = PPO.load(model_path, device="cpu")
    policy = model.policy
    print(f"[export] Model loaded: {model_path}")

    # ── Extract weights ───────────────────────────────────────────────────────
    # SB3 MlpPolicy  net_arch=dict(pi=[H,H]):
    #   policy.mlp_extractor.policy_net → [Linear, Tanh, Linear, Tanh]
    pnet = policy.mlp_extractor.policy_net
    W1 = pnet[0].weight.detach().numpy()            # (H, obs_dim)
    b1 = pnet[0].bias.detach().numpy()              # (H,)
    W2 = pnet[2].weight.detach().numpy()            # (H, H)
    b2 = pnet[2].bias.detach().numpy()              # (H,)
    W3 = policy.action_net.weight.detach().numpy()  # (act_dim, H)
    b3 = policy.action_net.bias.detach().numpy()    # (act_dim,)

    H, obs_dim, act_dim = W1.shape[0], W1.shape[1], W3.shape[0]
    kb = (W1.size + W2.size + W3.size + b1.size + b2.size + b3.size) * 4 / 1024
    print(f"[export] Network : {obs_dim} -> {H} -> {H} -> {act_dim}")
    print(f"[export] Weights : {kb:.0f} KB (float32)")
    if kb > 200:
        print("[export] NOTE: >200 KB – stored in Flash (.rodata). SRAM is fine.")

    # ── VecNormalize stats ────────────────────────────────────────────────────
    obs_mean = np.zeros(obs_dim, dtype=np.float32)
    obs_var  = np.ones(obs_dim,  dtype=np.float32)
    clip_obs = 10.0

    if vec_norm_path and os.path.exists(vec_norm_path):
        dummy    = DummyVecEnv([lambda: WhoopDroneEnv()])
        vn       = VecNormalize.load(vec_norm_path, dummy)
        obs_mean = vn.obs_rms.mean.astype(np.float32)
        obs_var  = vn.obs_rms.var.astype(np.float32)
        clip_obs = float(vn.clip_obs)
        dummy.close()
        print(f"[export] VecNormalize loaded: {vec_norm_path}")
    else:
        print("[export] WARNING: No VecNormalize – using identity normalisation.")

    # ── Build C header ────────────────────────────────────────────────────────
    lines = []

    lines += [
        "/*",
        " * AUTO-GENERATED by deploy/export_to_esp32.py  –  DO NOT EDIT MANUALLY",
        f" * Source  : {os.path.basename(model_path)}",
        f" * Network : {obs_dim} -> {H} -> {H} -> {act_dim}  ({kb:.0f} KB float32)",
        " *",
        " * Inference:",
        " *   x  = clip( (obs - OBS_MEAN) / sqrt(OBS_VAR + 1e-8),  +-CLIP_OBS )",
        " *   h1 = tanh( W1 @ x  + B1 )",
        " *   h2 = tanh( W2 @ h1 + B2 )",
        " *   y  = clip( W3 @ h2 + B3,  0, 1 )",
        " */",
        "",
        "#pragma once",
        "#include <math.h>",
        "",
        f"#define MODEL_OBS_DIM   {obs_dim}",
        f"#define MODEL_HIDDEN    {H}",
        f"#define MODEL_ACT_DIM   {act_dim}",
        f"#define MODEL_CLIP_OBS  {clip_obs:.4f}f",
        "",
        "/* ── VecNormalize ─────────────────────────────────────────────── */",
    ]
    lines += [_arr_to_c("OBS_MEAN", obs_mean)]
    lines += [_arr_to_c("OBS_VAR",  obs_var)]
    lines += [""]
    lines += ["/* ── Layer 1 ──────────────────────────────────────────────────── */"]
    lines += [_arr_to_c("W1", W1)]
    lines += [_arr_to_c("B1", b1)]
    lines += [""]
    lines += ["/* ── Layer 2 ──────────────────────────────────────────────────── */"]
    lines += [_arr_to_c("W2", W2)]
    lines += [_arr_to_c("B2", b2)]
    lines += [""]
    lines += ["/* ── Output layer ─────────────────────────────────────────────── */"]
    lines += [_arr_to_c("W3", W3)]
    lines += [_arr_to_c("B3", b3)]

    # Inference function
    lines += [
        "",
        "/* ── model_infer() ──────────────────────────────────────────────── */",
        "/*",
        " * obs[MODEL_OBS_DIM]  – raw (un-normalised) observation",
        " * act[MODEL_ACT_DIM]  – output motor throttles in [0, 1]",
        " */",
        "static inline void model_infer(const float* obs, float* act) {",
        f"    float x[{obs_dim}], h1[{H}], h2[{H}];",
        "    int i, j;",
        "",
        "    /* 1. Normalise */",
        f"    for (i = 0; i < {obs_dim}; i++) {{",
        "        float v = (obs[i] - OBS_MEAN[i]) / sqrtf(OBS_VAR[i] + 1e-8f);",
        "        if (v >  MODEL_CLIP_OBS) v =  MODEL_CLIP_OBS;",
        "        if (v < -MODEL_CLIP_OBS) v = -MODEL_CLIP_OBS;",
        "        x[i] = v;",
        "    }",
        "",
        "    /* 2. Layer 1: h1 = tanh(W1 @ x + b1) */",
        f"    for (i = 0; i < {H}; i++) {{",
        "        float s = B1[i];",
        f"        for (j = 0; j < {obs_dim}; j++) s += W1[i * {obs_dim} + j] * x[j];",
        "        h1[i] = tanhf(s);",
        "    }",
        "",
        "    /* 3. Layer 2: h2 = tanh(W2 @ h1 + b2) */",
        f"    for (i = 0; i < {H}; i++) {{",
        "        float s = B2[i];",
        f"        for (j = 0; j < {H}; j++) s += W2[i * {H} + j] * h1[j];",
        "        h2[i] = tanhf(s);",
        "    }",
        "",
        "    /* 4. Output: act = clip(W3 @ h2 + b3, 0, 1) */",
        f"    for (i = 0; i < {act_dim}; i++) {{",
        "        float s = B3[i];",
        f"        for (j = 0; j < {H}; j++) s += W3[i * {H} + j] * h2[j];",
        "        act[i] = s < 0.0f ? 0.0f : (s > 1.0f ? 1.0f : s);",
        "    }",
        "}",
        "",
    ]

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    size_kb = os.path.getsize(out_path) / 1024
    print(f"[export] Header written → {out_path}  ({size_kb:.0f} KB)")
    print()
    print("Next:")
    print(f"  cp {out_path}  firmware/esp32_standalone/")
    print("  Open firmware/esp32_standalone/esp32_standalone.ino in Arduino IDE and flash.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export PPO model to ESP32 C header")
    parser.add_argument("model_path",        help="Trained .zip model path")
    parser.add_argument("--norm",  default=None,
                        help="vec_normalize.pkl path (recommended)")
    parser.add_argument("--out",
                        default="firmware/esp32_standalone/model_weights.h",
                        help="Output .h file path")
    args = parser.parse_args()
    export(args.model_path, args.norm, args.out)
